### ISSUE TITLE
Values upto a certain step

### ISSUE THREAD

**Issue by supremeboy18** [zaguiini/formik-wizard#20]
Is there a way I can get access to the values up to a certain step?

Say I have 4 steps: A, B, C, and D.

A has 2 values (name and age)
B has 2 value (companyName and designation)
C has 3 value (street, zipcode and country)
D is the final step

I want to gain access to the values before step C that is (name, age, companyName, designation) at C. Is there any way I can get that?

**Comment by Hopp3r** [comment]
Pretty sure you can use the wizard context for that.

**Comment by supremeboy18** [comment]
Oh yes!! Thank you very much. I actually missed that part in the Usage section.

**Comment by ataravati** [comment]
@supremeboy18 @Hopp3r But, how do you access the wizard context from a step. I can access it from the form wrapper, but I don't know how to get access to it from inside the step.
