### ISSUE TITLE
GoToStep & onAction API call  response error

### ISSUE THREAD

**Issue by aneraghu** [zaguiini/formik-wizard#24]
Hi,
I was trying to use this in my project but I am stuck on 2 things.

1)  I am not able to go to a particular step. it always starts from the beginning. Please do let me know if any solution for that.

2) onAction call if any error in API response how to handle that.

**Comment by zaguiini** [comment]
1. `FormikWizard` exposes a prop called `albusProps` which you can use to [pass props directly to the underling `<Wizard />` component](https://github.com/americanexpress/react-albus#props). Also, in the FormikWizardContext (`useFormikWizard()`)  you also get access to the `wizard` object, which is the [`react-albus` context](https://github.com/americanexpress/react-albus#contextwizard) itself.

2. I didn't quite get it.

**Comment by ataravati** [comment]
@aneraghu If there are any errors in the API response, just catch and and then throw it again. If you don't throw the error the wizard goes to the next step, which in most cases is not what you want.
