### ISSUE TITLE
Give state from MultiForm to FormWrapper

### ISSUE THREAD

**Issue by brechtarnou** [zaguiini/formik-wizard#25]
Hi,

Is it possible to give state from my MultiForm to Formwrapper?

`function MultiForm(props) {
  console.log(props)
  const handleSubmit = React.useCallback(values => {
    console.log("full values:", values)

    return {
      message: "Thanks for submitting!",
    }
  }, [])

  return (
    <FormikWizard steps={steps} onSubmit={handleSubmit} render={FormWrapper} />
  )
}

export default MultiForm`

As you can see this is the MultiForm component, and I want to pass some state to my FormWrapper to render the correct button.

`function FormWrapper({
  children,
  isLastStep,
  status,
  goToPreviousStep,
  canGoBack,
  actionLabel,
  type,
}) {
  console.log(type)
  return (
    <div className="mt-24 text-center">
      {status ? (
        <div>
          {status.message}
          <hr />
        </div>
      ) : (
        <>
          {children}
          <div className="flex md:block">
            <StyledButton
              type="button"
              onClick={goToPreviousStep}
              hidden={!canGoBack}
              className="w-1/3 md:w-1/5 mx-4 rounded-sm"
            >
              Vorige
            </StyledButton>

            {type === "betalen" ? (
              <StyledButton
                type="submit"
                className="w-1/3 md:w-1/5 mx-4 rounded-sm"
              >
                {actionLabel || (isLastStep ? "Betaal nu" : "Volgende")}
              </StyledButton>
            ) : (
              <StyledButton
                type="submit"
                className="w-1/3 md:w-1/5 mx-4 rounded-sm"
              >
                {actionLabel || (isLastStep ? "Verzend PDF" : "Volgende")}
              </StyledButton>
            )}
          </div>
        </>
      )}
    </div>
  )
}
`
But the type prop I want to pass through is undefined in my FormWrapper.

Thanks in advance.

**Comment by zaguiini** [comment]
For those type of questions, StackOverflow is better suited. Please create a topic there describing your problem. Thanks!
