### ISSUE TITLE
How to change validationSchema conditionally

### ISSUE THREAD

**Issue by Bulletninja** [zaguiini/formik-wizard#28]
I've been able to use formik-wizard to build that, a wizard with validation succesfully, but i want my form to have some fields that are depended on others. For example, if you say "no" you might not need to answer more questions, but if you say "yes" you need to fill some more fields. How can i update my validationSchema to ignore those hidden/non-rendered fields?

**Comment by Bulletninja** [comment]
Nevermind, noticed this is more about the way i'm using yup, and not formik-wizard

**Comment by zaguiini** [comment]
Exactly, this is bound to `yup` and conditionals. check `yup.test({ when: boolean })` for more information.
