### ISSUE TITLE
Doesn't work with NextJS

### ISSUE THREAD

**Issue by corysimmons** [zaguiini/formik-wizard#3]
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

![image](https://user-images.githubusercontent.com/224636/58471929-0df48080-8113-11e9-8862-7e6453c1dbe7.png)

Copy/pasted your example.

**Comment by zaguiini** [comment]
I don't know NextJS :/ Can't help with this. Do you use it or know somebody who uses that?

**Comment by corysimmons** [comment]
It's React with all the SSR stuff. It's no problem.

**Comment by zaguiini** [comment]
Actually the problem was that this lib doesn't have the default export, so you needed to do `import { FormikWizard}`

But it's too late haha.

**Comment by corysimmons** [comment]
lol rip. I'll try this lib again sometime. My bad. :)
