### ISSUE TITLE
Can we move into Formik's monorepo + take this package name?

### ISSUE THREAD

**Issue by jaredpalmer** [zaguiini/formik-wizard#40]

**Comment by zaguiini** [comment]
Hey Jared, this is a really old project and I'm not sure about its architectural decisions anymore. I've been playing around and am with new plans. Please read #39. We can talk if you still want to move it, considering the bottleneck imposed by `react-albus`, but I would rather wait and see if the proposal materializes.

**Comment by jaredpalmer** [comment]
I meant mostly for the package name to move over. We'll be refactoring for sure

**Comment by zaguiini** [comment]
And what is the plan for the refactoring? Would I be involved? When would it take place?
