### ISSUE TITLE
Do not export FormikWizard as default export.

### ISSUE THREAD

**Issue by michelts** [zaguiini/formik-wizard#8]
Hi @zaguiini 

Jared palmer's tsdx [don't handle default exports very well](https://github.com/palmerhq/tsdx/issues/165).

To be able to use FormikWizard, I need to use the prop `default` from the default imported module:

```
import FormikWizard from 'formik-wizard';
...
<FormikWizard.default ... />
```

What do you think about using only named exports?

**Comment by zaguiini** [comment]
To be honest, I prefer default exports... And I'm not sure why but the example works with the default. But this looks to be a recurrent issue, so yes I'm open to that. Let's keep exporting the default, but lets name export `FormikWizard` as well. I'll create the PR.

**Comment by zaguiini** [comment]
Thanks for the heads up!

**Comment by michelts** [comment]
Hi @zaguiini 

Great! I think this is the best approach for the moment.

Thanks for the quick reply!
